elbow_silhouette:
  max_clusters: 20
  distance: 'braycurtis'
  njobs: -1
  random_state: 42
  visualize: True

kmedoids:
  k_values: [2]
  metric: 'braycurtis'
  random_state: 42
  save: False
  save_format: 'csv'

analysis:
  n_clusters: 5
  metric: 'euclidean'
  random_state: 42
  save: False
  save_format: 'csv'
  visualize: True
  useless_metadata:            
    - 'samples'
    - 'SRA'
    - 'BioProject'
    - 'Platform'
    - 'Bases'
    - 'avgSpotLen'
    - 'LibraryLayout'
    - 'medoids'
    - 'submedoids'