pca:
  n_components: -1

kernelpca:
  n_components: -1
  kernel: 'rbf'
  gamma: 0.0001

pcoa:
  metric: 'braycurtis'

tsne:
  n_components: 3
  random_state: 42
  metric: 'euclidean'
  max_iter: 3000
  perplexity: 25
  learning_rate: 100

pls_regression:
  n_components: 3


