cross_val:
  classifier: 'SVC'
  transformation: 'CLRTransformer'
  scaler: 'StandardScaler'
  n_splits: 2
  random_state: 42
  save: True
  visualize: True
  njobs: -1
  scorings: 
    - accuracy 
    - precision
    - recall
    - f1
    - roc_auc
  param_grid:
    "classifier__kernel": "['linear', 'rbf']"
    "classifier__C": "np.logspace(-4,4,15)"
    "classifier__gamma": "['scale', 'auto', 0.001, 0.01]"
    "classifier__random_state": "[42]"
