cross_val:
  pipeline:
    classifier: 'RF'
    transformation: 'CLR'
    scaler: 'Standard'
    smote: False
    reduction: 'None'
  classifier_params: # Parameters for RandomForestClassifier
    n_estimators: 500
    random_state: 42
    class_weight: 'balanced'
    n_jobs: -1

  n_folds: 5
  random_state: 42
  shuffle: True
  save: False
  visualize: False
  njobs: -1
  save_format: 'csv'  # For metrics DataFrame

  scorings: 
    - accuracy 
    - precision
    - recall
    - f1
    - roc_auc

optuna:
  pipeline:
    classifier: 'XGB'
    transformation: 'CLR'
    scaler: 'Standard'
    smote: False
    reduction: 'None'
  classifier_params: # Parametri specifici per XGBClassifier
    n_estimators: 200
    learning_rate: 0.1
    random_state: 42

  n_trials: 3
  direction: 'maximize'
  scoring: 'accuracy'
  shuffle: True
  random_state: 42
  save: False
  save_format: 'csv'
  njobs: -1